### ISSUE TITLE
ModuleNotFoundError: No module named 'pyspark'

### ISSUE THREAD

**Issue by TanUkkii007** [nii-yamagishilab/self-attention-tacotron#12]
> @moonnee Your git version is old so please install the latest version.
> 
> FYI my git version is 2.17.1.
> 
> ```
> git --version
> git version 2.17.1
> ```
> Updating git may solve your ploblems.
> 
> I also updated the Bazel documentation for clearity.
> https://github.com/nii-yamagishilab/self-attention-tacotron/blob/583e0255daa8a1093f5a0ca37e3b5faafbdca106/Bazel.md

I upgraded my git to 2.20.1, and got new errors after running preprocessing commonds:
`bazel run preprocess_ljspeech -- --source-only --hparam-json-file=./examples/ljspeech/self-attention-tacotron.json /data/LJSpeech-1.1 exp/github/self-attention-tacotron/training/source`

> Starting local Bazel server and connecting to it...
> INFO: Invocation ID: 644adc8d-7603-4cd2-a91e-70dcf3efbef3
> INFO: Analysed target //:preprocess_ljspeech (14 packages loaded, 119 targets configured).
> INFO: Found 1 target...
> Target //:preprocess_ljspeech up-to-date:
>   bazel-out/k8-py3-fastbuild/bin/preprocess_ljspeech
> INFO: Elapsed time: 26.432s, Critical Path: 0.03s
> INFO: 0 processes.
> INFO: Build completed successfully, 4 total actions
> INFO: Running command line: bazel-out/k8-py3-fastbuild/bin/preprocess_ljspeech --source-only '--hparam-json-file=./examples/ljspeech/self-attention-tacotron.json' /data/LJSpeech-1.1 /project/bdda/y
> INFO: Build completed successfully, 4 total actions
> Traceback (most recent call last):
>   File "/.cache/bazel/_bazel/5a5901de42a7f8700ed00205840ff26a/execroot/__main__/bazel-out/k8-py3-fastbuild/bin/preprocess_ljspeech.runfiles/__main__/preprocess_ljspeech.py", line 23, in <module>
>     from pyspark import SparkContext
> ModuleNotFoundError: No module named 'pyspark'

But I already installed pyspark.

> Requirement already satisfied: pyspark in /users/anaconda3/lib/python3.6/site-packages (2.4.0)
> Requirement already satisfied: py4j==0.10.7 in /users/anaconda3/lib/python3.6/site-packages (from pyspark) (0.10.7)
 I searched a lot but didn't figure out why. Do you know the possible reason？ Thank you.

_Originally posted by @moonnee in https://github.com/nii-yamagishilab/self-attention-tacotron/issues/7#issuecomment-454757653_

**Comment by TanUkkii007** [comment]
I confirmed that command works in my environment.
Make sure you are using right python environment. Checking `which python` and `conda list`may help.

**Comment by moonnee** [comment]
> I confirmed that command works in my environment.
> Make sure you are using right python environment. Checking `which python` and `conda list`may help.

Thank you for your reply. I checked the python environment and used ` conda install pyspark ` instead of `pip install pyspark`. That problem was solved. But another one occurred:

> Traceback (most recent call last):
>   File "/.cache/bazel/_bazel/5a5901de42a7f8700ed00205840ff26a/execroot/__main__/bazel-out/k8-py3-fastbuild/bin/preprocess_ljspeech", line 8, in <module>    import subprocess
>   File "/anaconda3/lib/python3.6/subprocess.py", line 136, in <module>
>     import _posixsubprocess
> ImportError: /tf1.3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Py_set_inheritable_async_safe

It seems that there is something wrong with my tensorflow(1.3.0), but don't know how to  solve it.  Any help? Thank you.

**Comment by TanUkkii007** [comment]
@moonnee tensorflow 1.3.0 is not supported. Please use version >= 1.11. The dependencies are documented in README.
