### ISSUE TITLE
Can't start training adding features.accent_type

### ISSUE THREAD

**Issue by heizari** [nii-yamagishilab/self-attention-tacotron#34]
Hello. I try to synthesis Japanese audios that aware accent.

I used original Japanese corpus like JSUT.
To preprocess, I modified [datasets/ljspeech/dataset.py](https://github.com/nii-yamagishilab/self-attention-tacotron/blob/master/datasets/ljspeech/dataset.py) and [preprocess/ljspeech.py](https://github.com/nii-yamagishilab/self-attention-tacotron/blob/master/preprocess/ljspeech.py) to add accent_type, reffering to [issue#24](https://github.com/nii-yamagishilab/self-attention-tacotron/issues/24#issuecomment-547242057).
Accent_type is id sequence like source.(cf:[1,1,1,2,2,0,0,0,1,1])

With these settings, I've created tfrecords.
However when I start training, I got following error message.
I tried to add `tf.enable_eager_execution()`. But it's not work.

Is this some wrong way to create tfrecords?

Thank you!!

```  File "train.py", line 157, in <module>
    main()
  File "train.py", line 151, in main
    use_multi_gpu)
  File "train.py", line 92, in train_and_evaluate
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1191, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "self-attention-tacotron/models/models.py", line 369, in model_fn
    embedding_output, input_lengths=features.source_length)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 547, in __iter__
    self._disallow_iteration()
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 543, in _disallow_iteration
    self._disallow_in_graph_mode("iterating over `tf.Tensor`")
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 523, in _disallow_in_graph_mode
    " this function with @tf.function.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.```

**Comment by TanUkkii007** [comment]
@heizari Could you tell me which encoder you are using?
If you are using encoder not supporting accent_type, please replace it with one supporting it, for example, `EncoderV1WithAccentType`.
https://github.com/nii-yamagishilab/self-attention-tacotron/blob/master/hparams.py#L64

**Comment by heizari** [comment]
@TanUkkii007 I'm using `EncoderV1WithAccentType`  as an encoder, `DualSourceDecoder` as a decoder and `DualSourceSelfAttentionTacotronModel` as a tacotron model

**Comment by TanUkkii007** [comment]
@heizari Could you try `SelfAttentionCBHGEncoderWithAccentType` instead of `EncoderV1WithAccentType`?  The `DualSourceSelfAttentionTacotronModel` requires two inputs from encoder, so you need to use `SelfAttentionCBHGEncoderWithAccentType`, which return two outputs.
https://github.com/nii-yamagishilab/self-attention-tacotron/blob/0ebd96114feab5a499964402a8ab7e402f0083b4/modules/module.py#L438

**Comment by heizari** [comment]
and I changed tacotron model to `ExtendedTacotronV1Model`, I got following error message
```
Traceback (most recent call last):
  File "train.py", line 157, in <module>
    main()
  File "train.py", line 151, in main
    use_multi_gpu)
  File "train.py", line 92, in train_and_evaluate
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1191, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1149, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "~/user/self-attention-tacotron/models/models.py", line 64, in model_fn
    apply_dropout_on_inference=params.apply_dropout_on_inference)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_core/python/layers/base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in converted code:


    TypeError: tf__call() got an unexpected keyword argument 'attention_fn'

```

**Comment by TanUkkii007** [comment]
@heizari  It makes sense that you got errors when you use incompatible combination of models and encoder. Please try the allowed combinations as below.
|  |model  |encoder  |decoder|
|---|---|---|---|
| Tacotron  |ExtendedTacotronV1Model  |EncoderV1WithAccentType  |ExtendedDecoder|
|Self-attention Tacotron  |DualSourceSelfAttentionTacotronModel  |SelfAttentionCBHGEncoderWithAccentType  |DualSourceTransformerDecoder |

https://github.com/nii-yamagishilab/self-attention-tacotron/blob/master/examples/ljspeech/tacotron.json#L183-L185
https://github.com/nii-yamagishilab/self-attention-tacotron/blob/master/examples/ljspeech/self-attention-tacotron.json#L183-L185

**Comment by heizari** [comment]
@TanUkkii007 Thanks your replies! Ican start training on this setting
